title:               Paul Garnier
url:                 https://DonsetPG.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Paul Garnier
  url:               DonsetPG.github.io
  email:             paul.garnier@mines-paristech.fr

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
